In [20]:
!pip install pyyaml pandas numpy sqlalchemy psycopg2-binary pymysql

Requirement already satisfied: pyyaml in d:\guvi class\stock_mge_pro\venv\lib\site-packages (6.0.1)
Requirement already satisfied: pandas in d:\guvi class\stock_mge_pro\venv\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in d:\guvi class\stock_mge_pro\venv\lib\site-packages (1.26.4)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\guvi class\stock_mge_pro\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\guvi class\stock_mge_pro\venv\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in d:\guvi class\stock_mge_pro\venv\lib\site-packages (from pandas) (2026.2)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\guvi class\stock_mge_pro\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in d:\guvi class\stock_mge_pro\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl (2.1 MB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.8 MB 2.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.8 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.5 MB/s eta 0:00:00
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.0-cp312-cp312-win_amd64.whl (238 kB)
Installing collected packages: pymysql, psycopg2-binary, greenlet, sqlalchemy
Successfully installed greenlet-3.5.0 psycopg2-binary-2.9.12 pymysql-1.1.3 sqlalchemy-2.0.49

[notice] A new release of pip is available: 25.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import pandas as pd
import os
import yaml
import numpy as np
from sqlalchemy import create_engine

# Data Extraction and Transformation: 
 ● Data is provided in YAML format, organized by months. 

 ● Within each month's folder, there are date-wise data entries. 

 ● The task is to extract this data from the YAML file and transform it into a CSV 
 format, organized by symbols  
 
 ● This will result in 50 CSV files after the extraction process, one for each symbol 
 or data category

In [27]:
root_folder = r'D:\Guvi Class\stock_Mge_pro\data'
output_dir = r'D:\Guvi Class\stock_Mge_pro\After_extract_data'
date_folders=os.listdir(root_folder)
all_datas=[]
try:
    for i in date_folders:
        file_folders=os.listdir(os.path.join(root_folder,i))
        for j in file_folders:
            with open(os.path.join(root_folder, i,j), "r") as file:
                data = yaml.safe_load(file)
                all_datas.extend(data)
    df=pd.DataFrame(all_datas)
    for ticker, group in df.groupby('Ticker'):
        file_path = os.path.join(output_dir, f"{ticker}.csv")
        group.to_csv(file_path, index=False)
except Exception as e:
    print(e)

In [28]:
dfs=[]
output_dir = r'D:\Guvi Class\stock_Mge_pro\After_extract_data'
for file in os.listdir(output_dir):
    file_path = os.path.join(output_dir, file)
    data = pd.read_csv(file_path)
    dfs.append(data)
df = pd.concat(dfs, ignore_index=True)
df.shape

(14200, 8)

In [29]:
df.head()

,Ticker,close,date,high,low,month,open,volume
0,ADANIENT,2387.25,2023-10-03 05:30:00,2424.90,2372.00,2023-10,2418.00,2019899
1,ADANIENT,2464.95,2023-10-04 05:30:00,2502.75,2392.25,2023-10,2402.20,2857377
2,ADANIENT,2466.35,2023-10-05 05:30:00,2486.50,2446.40,2023-10,2477.95,1132455
3,ADANIENT,2478.10,2023-10-06 05:30:00,2514.95,2466.05,2023-10,2466.35,1510035
4,ADANIENT,2442.60,2023-10-09 05:30:00,2459.70,2411.30,2023-10,2440.00,1408224

In [30]:
df.tail()

,Ticker,close,date,high,low,month,open,volume
14195,WIPRO,566.70,2024-11-14 05:30:00,574.55,564.2,2024-11,568.95,4891760
14196,WIPRO,552.85,2024-11-18 05:30:00,566.70,540.3,2024-11,566.70,7644882
14197,WIPRO,562.00,2024-11-19 05:30:00,569.80,554.7,2024-11,556.00,6459889
14198,WIPRO,557.15,2024-11-21 05:30:00,567.60,555.3,2024-11,562.00,5836304
14199,WIPRO,571.65,2024-11-22 05:30:00,573.60,557.9,2024-11,561.95,7366616

In [31]:
df.sample(n=5)

,Ticker,close,date,high,low,month,open,volume
1009,ASIANPAINT,2885.75,2024-05-22 05:30:00,2895.00,2836.60,2024-05,2851.80,933846
4322,EICHERMOT,3892.50,2024-01-02 05:30:00,4010.75,3882.35,2024-01,4010.10,1221148
9764,ONGC,280.25,2024-03-06 05:30:00,284.30,273.55,2024-03,284.30,16807149
2529,BEL,288.85,2024-10-15 05:30:00,289.45,285.75,2024-10,287.15,14701531
13029,TECHM,1604.05,2024-10-03 05:30:00,1631.15,1596.15,2024-10,1615.00,2332279

In [32]:
df.isna().sum() # Checking Null Valus

Ticker    0
close     0
date      0
high      0
low       0
month     0
open      0
volume    0
dtype: int64

In [33]:
df.duplicated().sum() #Checking Duplicated

0

In [34]:
df.dtypes # Checking the Data types

Ticker     object
close     float64
date       object
high      float64
low       float64
month      object
open      float64
volume      int64
dtype: object

In [35]:
df['date']=pd.to_datetime(df['date']) # Convert Object in to Date Type

In [41]:


engine = create_engine(
    "postgresql+psycopg2://postgres:12345@localhost:5432/Stock_Db"
)

In [42]:
engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/Stock_Db)

In [44]:
df.to_sql(
    'stock_data',
    engine,
    index=False,
    if_exists='append',
    chunksize=1000,
    method='multi'
)

14200